./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/6.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/7.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/8.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/9.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/10.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/11.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/12.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/13.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/14.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/15.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/16.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/17.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/18.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/19.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/20.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/21.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/22.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/23.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/24.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/25.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/26.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/27.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/28.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/29.py 0
./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tless_SO/30.py 0