#FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04
FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV USER_NAME=appuser
ENV USER_HOME=/home/${USER_NAME}

# Create a new user with a home directory
RUN useradd -m -d ${USER_HOME} -s /bin/bash ${USER_NAME} && \
    chown -R ${USER_NAME}:${USER_NAME} ${USER_HOME}

# Update package list and install required packages
RUN apt-get update && apt-get install -y \
    python3-opencv ca-certificates python3-dev git wget sudo ninja-build \
    libjpeg-dev zlib1g-dev libopenexr-dev openexr libglfw3-dev libglfw3 \
    libglew-dev libassimp-dev libnuma-dev clang curl autoconf libtool \
    libeigen3-dev libgoogle-glog-dev libsuitesparse-dev libatlas-base-dev \
    cmake curl pkg-config libgles2 libgl1-mesa-dev libegl1-mesa-dev \
    libgles2-mesa-dev libglvnd0 libgl1 libglx0 libegl1 libglvnd-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to the new user
USER ${USER_NAME}

# Create a directory for the application
RUN mkdir ${USER_HOME}/gdrnpp_bop2022
WORKDIR ${USER_HOME}/gdrnpp_bop2022

# Create a symbolic link for python
RUN ln -sv /usr/bin/python3 /usr/bin/python

# Install pip
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py "pip<24.1" && \
    rm get-pip.py

# Install required Python packages
RUN pip install tensorboard cmake onnx setuptools==69.5.1
RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install 'git+https://github.com/facebookresearch/fvcore'
RUN pip install 'git+https://github.com/facebookresearch/detectron2'

# Copy and install additional requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

ENV FORCE_CUDA="1"
ARG TORCH_CUDA_ARCH_LIST="Maxwell;Maxwell+Tegra;Pascal;Volta;Turing;Ada"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

# Ensure the working directory is owned by the user
RUN chown -R ${USER_NAME}:${USER_NAME} ${USER_HOME}/gdrnpp_bop2022

# Switch to the working directory
WORKDIR ${USER_HOME}/gdrnpp_bop2022
