names:
    1: "obj_000001"  # Add your coordinates here
    2: "obj_000002"  # Add your coordinates here
    3: "obj_000003"  # Add your coordinates here
    4: "obj_000004"  # Add your coordinates here
    5: "obj_000005"  # Add your coordinates here
    6: "obj_000006"  # Add your coordinates here
    7: "obj_000007"  # Add your coordinates here
    8: "obj_000008"  # Add your coordinates here
    9: "obj_000009"  # Add your coordinates here
    10: "obj_000010"  # Add your coordinates here
    11: "obj_000011"  # Add your coordinates here
    12: "obj_000012"  # Add your coordinates here
    13: "obj_000013"  # Add your coordinates here
    14: "obj_000014"  # Add your coordinates here
    15: "obj_000015"  # Add your coordinates here
    16: "obj_000016"  # Add your coordinates here
    17: "obj_000017"  # Add your coordinates here
    18: "obj_000018"  # Add your coordinates here
    19: "obj_000019"  # Add your coordinates here
    20: "obj_000020"  # Add your coordinates here